version: '3.8'

services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: reto_user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: reto_db_utf8
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
